### ISSUE TITLE
ERROR : Exception in ASGI application

### ISSUE THREAD

**Issue by mic050r** [2024-Mirim-Dancing/Dancing_Back#8]
<details>
  <summary>#7 하면서 발생한 에러</summary>
![image](https://github.com/2024-Mirim-Dancing/Dancing_Back/assets/103114387/51eaa7d5-6c60-440b-980c-e5bf3709a4d4)
</details>

**Comment by mic050r** [comment]
=> **이 오류는 MongoDB 서버와의 연결 문제를 나타내며, 연결이 거부되었음을 나타낸다.**

아래와 같이 코드 변경 후 에러 fix
1. **Docker Compose 파일 수정**: 이전에 제안된 Docker Compose 파일에 몇 가지 변경 사항이 필요합니다.

```yaml
version: "3"

services:
  fastapi-mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    links:
      - mongo:mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
```

변경된 부분은 `links` 섹션입니다. 여기서 `mongo:mongo`는 FastAPI 컨테이너와 MongoDB 컨테이너를 연결하는 링크입니다. 이렇게 하면 FastAPI 컨테이너에서 `mongo` 호스트 이름을 사용하여 MongoDB에 연결할 수 있습니다.

2. **FastAPI 코드 수정**: MongoDB 연결 URI를 Docker Compose 파일에서 전달된 환경 변수에서 가져와야 합니다.

```python
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pymongo import MongoClient
import os

app = FastAPI()

# MongoDB 연결
mongo_uri = os.getenv("MONGO_URI")  # 환경 변수에서 URI 가져오기
client = MongoClient(mongo_uri)
db = client["admin"]
user_collection = db["user"]

# 나머지 코드는 변경되지 않음
```

> chatgpt를 활용하여 에러 수정

**Comment by mic050r** [comment]
### Links란?
=> Docker Compose 파일에서 `links` 섹션은 서비스 간의 연결을 설정하는 데 사용된다.

**Links**:
- **개념**: `links`는 한 컨테이너 내부의 서비스가 다른 컨테이너의 서비스에 접근할 수 있도록 허용.
ex) FastAPI 애플리케이션과 MongoDB 데이터베이스가 각각 다른 컨테이너에서 실행되는 경우, FastAPI 컨테이너가 MongoDB에 연결하려면 이러한 연결을 설정해야 한다!

- **사용**: `links`는 다음과 같이 사용
  
  ```yaml
  services:
    service1:
      ...
    service2:
      ...
      links:
        - service1:alias
  ```
  
  여기서 `service2`는 `service1`을 `alias`로 링크한다. 이렇게 하면 `service2` 내부에서 `alias`를 사용하여 `service1`에 액세스할 수 있다.

**Comment by mic050r** [comment]
### links를 network로 수정하기 
```yml
version: "3"

services:
  fastapi-mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - 2024md
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - 2024md

networks:
  2024md:
```
